name: Java CI

on: [push, pull_request]

jobs:
  run_tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 14
      - name: Build with Maven
        run: mvn -B package -DskipTests --file pom.xml
      - name: Run tests
        run: mvn -B test --file pom.xml
